### ISSUE TITLE
Linking to a named anchor visits page with subtitle hidden under menu

### ISSUE THREAD

**Issue by Daanvm** [mollie/api-documentation#64] opened 2018-05-08 12:38 UTC
When you visit a page with a named anchor (e.g. /guides/recurring#guides-recurring-first-payment), the page opens with the title and first part of the paragraph you're linked to hidden under the menu, like this:

![screen shot 2018-05-08 at 14 35 58](https://user-images.githubusercontent.com/1397121/39757527-643b8346-52cd-11e8-9d61-8f07fe11456c.png)

**Comment by willemstuursma** [comment] 2018-05-09 13:51
Duplicate of #57 .

**Comment by Daanvm** [comment] 2018-05-11 10:46
I don't think this is a duplicate. This issue is about the menu bar overlapping the first part of the paragraph that you're linked to.

**Closed** 2018-05-23 12:06 UTC
