### ISSUE TITLE
pip vs pip3 and python vs python3

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#128] opened 2018-07-20 10:04 UTC
I'm no Python expert, so I'm not entirely sure what's going on here. Probably has to do with my local Python / Bash setup.

`make install` and `make html`  only worked for if I made this update to the `Makefile`:

```python
# ...

# SPHINXBUILD    = python -msphinx # old
SPHINXBUILD    = python3 -msphinx # new

#...

install:
	# pip install -U -r requirements.txt #old
	pip3 install -U -r requirements.txt #new

#...
```

Perhaps this should be noted in the `readme.md`? Otherwise, feel free to close.

**Comment by willemstuursma** [comment] 2018-07-20 10:06
Do you use Windows?

**Comment by sandervanhooft** [comment] 2018-07-20 10:08
MacOSX, High Sierra, latest (10.13.5)

**Comment by willemstuursma** [comment] 2018-07-20 10:41
@mvdpanne ?

**Comment by mvdpanne** [comment] 2018-07-20 12:46
Hey Sander,

I just tried running the commands on Python 2.7.9, and it actually failed at first as well. As you indicated, Python 3.x is not affected. It indicated some SSL problem:
```
There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION]
```

This seems to have to do with the Python.org websites no longer supporting TLS 1.0 and 1.1. Please try updating `pip` using the [following post](https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies/49748494#49748494). Afterwards, the commands worked fine.

**Comment by mvdpanne** [comment] 2018-07-23 08:03
I take it the problem is now resolved, and therefore I will close this issue.

**Closed by mvdpanne** 2018-07-23 08:03 UTC
