### ISSUE TITLE
Show 404 if page doesn't exists anymore

### ISSUE THREAD

**Issue by ndijkstra** [mollie/api-documentation#191] opened 2018-09-03 07:36 UTC
We've moved some pages, but if you visit the old url you can still see the page (but without css).

Examples: 
https://docs.mollie.com/guides/recurring
https://docs.mollie.com/guides/multicurrency

It is more convenient to show an error 404, or redirect the visitor to the correct page.

**Comment by vernondegoede** [comment] 2018-09-03 08:00
Duplicate of #190

**Closed** 2018-09-03 08:00 UTC
